Revert "bpf: Drop redundant hash_buf from map_get_hash operation"
/tmp/next/build/security/hornet/hornet_lsm.c:212:36: error: too many arguments to function call, expected 1, have 3
  212 |                         if (map->ops->map_get_hash(map, SHA256_DIGEST_SIZE, hash))
      |                             ~~~~~~~~~~~~~~~~~~~~~~      ^~~~~~~~~~~~~~~~~~~~~~~~
/tmp/next/build/include/crypto/sha2.h:14:33: note: expanded from macro 'SHA256_DIGEST_SIZE'
   14 | #define SHA256_DIGEST_SIZE      32
      |                                 ^

This reverts commit c48c3a7e7d5bed644208ed443d63bb6a6f411676.

Signed-off-by: Mark Brown <broonie@kernel.org>